site_name: PyTuDe - Python Tutorial auf Deutsch
site_description: deutschsprachiges Einsteiger Tutorial für die Programmiersprache Python
site_author: noisefloor
theme:
  name: readthedocs
  lang: de
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - admonition
nav:
  - 'start.md'
  - 'appetite.md'
  - 'interpreter.md'
  - 'introduction.md'
  - 'controlflow.md'
  - 'datastructures.md'
  - 'modules.md'
  - 'inputoutput.md'
  - 'errors.md'
  - 'classes.md'
  - 'stdlib.md'
  - 'venv.md'
  - 'whatnow.md'
  - 'remarks.md'
  - 'externallibs.md'
