site_name: PyTuDe - Python Tutorial auf Deutsch
site_description: deutschsprachiges Einsteiger Tutorial für die Programmiersprache Python
site_author: noisefloor
theme:
  name: readthedocs
  lang: de
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
